### ISSUE TITLE
Failing to upload when board Leonardo chosen

### ISSUE THREAD

**Issue by alexcroox** [Makeblock-official/XY-Plotter-2.0#14]
When I plug the ME board into my OSX laptop I can't upload the firmware when selecting board Leonardo as suggested in the documentation. 

`avrdude: butterfly_recv(): programmer is not responding`

However if I choose Uno it uploads OK.

When I try to run the GRemote java app in this repo it hangs on this screen:

![ss](http://al3x.me/dZeq/d)

(I had to install the CH340 driver for my Mac to even pick up the board via USB)

**Comment by lipsumar** [comment]
I have the same situation:
- had to first install CH340 driver for my Mac (10.9) to see the device
- had to symlink the crazy port name (cu.wch ch341 USB=>RS232 1450), this helped: http://0xcf.com/2015/03/13/chinese-arduinos-with-ch340-ch341-serial-usb-chip-on-os-x-yosemite/
- had to change board to "Uno" to be able to upload to the board

I now get the same error message:
<pre>Exception in thread "Animation Thread" java.lang.ArrayIndexOutOfBoundsException: 711
	at controlP5.BitFont.getGlyph(Unknown Source)
	[...]</pre>

**Comment by bedeau** [comment]
i have exactly the same problem, i think it's because of the fact that the plotter seems to be able to handle both me orion (base on uno) and me baseboard (base on leonardo). Given that the instruction tells us to use leonardo, i guess that the firmware was made by people owning a baseboard instead of an orion, which would explain our problems. My colleague says that he has a working version for the orion so he'll bring it tomorrow and we'll see if it does really works, and if it does i'll give it to you guys.

**Comment by lipsumar** [comment]
As for my problem, I realized I used a power source 10x less than the one in the box (330mA vs 3A) so I'm pretty sure that's the problem in my case. 
Unfortunately I'm in a remote location right now and can't test the proper power source. 
I'll update when I can. 

Emmanuel

**Comment by alexcroox** [comment]
@bedeau that was the resolution for us in the end (sorry re-visiting this topic after a few months!). The instructions are so poor for this product...

**Comment by timpulver** [comment]
How do you guys made it work? I can upload the Arduino-code using an external driver, but when I select the serial-port in GRemote I hear a short sound from one of the motors but nothing happens. 

<img width="512" alt="bildschirmfoto 2016-02-28 um 12 33 56" src="https://cloud.githubusercontent.com/assets/1055819/13379010/22e974ea-de1a-11e5-9d91-3d0ca4fe5e5b.png">
<img width="512" alt="bildschirmfoto 2016-02-28 um 12 34 11" src="https://cloud.githubusercontent.com/assets/1055819/13379011/22f0e9aa-de1a-11e5-9a5c-276e838e2211.png">

**Comment by timpulver** [comment]
Okay, using the power supply from the kit with a US —> EU adapter and selecting the right board in Arduino (`Uno` for the orion board) fixed it… Another less powerful power adapter did not work.
